config/routes.rb
Rails.application.routes.draw do
  resources :locations do   
    get "delete" 
  end

  resources :customers do   
    get "delete" 
  end

  resources :drivers do   
    get "delete" 
  end

  resources :expenses do   
    get "delete" 
  end
  resources :bookings do   
    get "delete" 
  end
  resources :rentals do   
    get "delete" 
  end
  resources :orders do   
    get "delete" 
  end
  resources :expense_types, path: "expense-types" do   
    get "delete" 
  end
  resources :maintenances do   
    get "delete" 
  end
  resources :consumptions do   
    get "delete" 
  end
  resources :intervention_types do   
    get "delete" 
  end
  resources :maintenance_types, path: "maintenance-types" do   
    get "delete" 
  end
  resources :vehicle_models do   
    get "delete" 
  end
  resources :odometers do   
    get "delete" 
  end
  
  resources :technical_visits do   
    get "delete" 
  end
  resources :insurances do   
    get "delete" 
  end
  resources :insurers do   
    get "delete" 
  end 
  resources :incidents do   
    get "delete" 
  end
  resources :parks do   
    get "delete" 
  end
  resources :gears do   
    get "delete" 
  end
  resources :gear_types, path: "gear-types" do   
    get "delete" 
  end
  resources :profiles do   
    get "delete" 
  end
  resources :permission_items do   
    get "delete" 
  end
  resources :permissions do   
    get "delete" 
  end
  resources :features do   
    get "delete" 
  end
  resources :roles do   
    get "delete" 
  end
  #root to: "front#home"

  get "/dashboard" => "dashboard#index", as: :dashboard
  resources :profiles do   
    get "delete" 
  end
  resources :permission_items do   
    get "delete" 
  end
  resources :permissions do   
    get "delete" 
  end
  resources :features do   
    get "delete" 
  end
  resources :roles do   
    get "delete" 
  end

  scope "account" do 
    resources :profiles 
    get "profile/:uid" => "profiles#edit", as: :edit_account
  end

  
  get "/users"     => "custom_users#index", as: :all_users 
  get "/users/unregistered"     => "custom_users#unregistered", as: :unregistered_commission_percentage 
  post "/users/new"     => "custom_users#create", as: :create_user
  get "/users/new"     => "custom_users#new", as: :new_user
  get "/user/edit/:id" => "custom_users#edit", as: :edit_user
  patch "/user/update/:id" => "custom_users#update", as: :update_user
  delete "/user/destroy/:id" => "custom_users#destroy", as: :destroy_user
  get "/user/delete/:id" => "custom_users#delete", as: :delete_user


  
  get "/user/enable/:id" => "custom_users#get_enable", as: :get_enable_user_account
  post "/user/enable/:id" => "custom_users#post_enable", as: :post_enable_user_account
  get "/user/disable/:id" => "custom_users#get_disable", as: :get_disable_user_account
  post "/user/disable/:id" => "custom_users#post_disable", as: :post_disable_user_account


  devise_for :users, path: '', controllers: { 
    registrations: "users/registrations",
    confirmations: 'users/confirmations',
    passwords: "users/passwords",
    sessions: "users/sessions"
        
    }, 
    path_names: {
        sign_in: 'login', 
        sign_out: 'logout', 
        password: 'secret', 
        confirmation: 'verification', 
        unlock: 'unblock', 
        registration: 'signup', 
        sign_up: '' 
    }
   
    devise_scope :user do
      root to: "users/sessions#new"
      authenticated :user do
        root 'dashboard#index', as: :authenticated_root
      end
  
      unauthenticated do
        root 'users/sessions#new', as: :unauthenticated_root
      end
    end


    # Dynamic error pages
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unacceptable"
    get "/500", to: "errors#internal_error"

    #mount Ckeditor::Engine => '/ckeditor'
  # For mobile API Endpoint
  #mount API::Base, at: "/"
end

app/models/insurance.rb
# == Schema Information
#
# Table name: insurances
#
#  id                   :bigint           not null, primary key
#  insurer_id           :bigint
#  gear_id              :bigint
#  start_date           :datetime
#  end_date             :datetime
#  insurance_number     :string
#  pre_tax_amount       :float            default(0.0)
#  vat_rate             :float            default(0.0)
#  vat_amount           :float            default(0.0)
#  amount_including_tax :float            default(0.0)
#  status               :string
#  user_id              :bigint
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Insurance < ApplicationRecord
	include SharedUtils::Generate

  before_save :generate_random_number_uid
  
  belongs_to :user

  # Change default params ID to uid
  def to_param
    uid
  end

end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  # GET /insurances
  # GET /insurances.json
  def index
    @insurances = Insurance.all
  end

  # GET /insurances/1
  # GET /insurances/1.json
  def show
  end

  # GET /insurances/new
  def new
    @insurance = Insurance.new
  end

  # GET /insurances/1/edit
  def edit
  end

  # POST /insurances
  # POST /insurances.json
  def create
    @insurance = Insurance.new(insurance_params)

    respond_to do |format|
      if @insurance.save
        format.html { redirect_to @insurance, notice: 'Insurance was successfully created.' }
        format.json { render :show, status: :created, location: @insurance }
      else
        format.html { render :new }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurances/1
  # PATCH/PUT /insurances/1.json
  def update
    respond_to do |format|
      if @insurance.update(insurance_params)
        format.html { redirect_to @insurance, notice: 'Insurance was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance }
      else
        format.html { render :edit }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurances/1
  # DELETE /insurances/1.json
  def destroy
    @insurance.destroy
    respond_to do |format|
      format.html { redirect_to insurances_url, notice: 'Insurance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def insurance_params
      params.require(:insurance).permit(:insurer_id, :vehicule_id, :start_date, :end_date, :insurance_number, :pre_tax_amount, :vat_rate, :amount_including_tax, :status, :user_id)
    end
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/views/insurances/_form.html.erb
<%= form_with(model: insurance, local: true) do |form| %>
  <% if insurance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insurance.errors.count, "error") %> prohibited this insurance from being saved:</h2>

      <ul>
      <% insurance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :insurer_id %>
    <%= form.text_field :insurer_id %>
  </div>

  <div class="field">
    <%= form.label :vehicule_id %>
    <%= form.text_field :vehicule_id %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :insurance_number %>
    <%= form.text_field :insurance_number %>
  </div>

  <div class="field">
    <%= form.label :pre_tax_amount %>
    <%= form.text_field :pre_tax_amount %>
  </div>

  <div class="field">
    <%= form.label :vat_rate %>
    <%= form.text_field :vat_rate %>
  </div>

  <div class="field">
    <%= form.label :amount_including_tax %>
    <%= form.text_field :amount_including_tax %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/insurances/edit.html.erb
<h1>Editing Insurance</h1>

<%= render 'form', insurance: @insurance %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

app/views/insurances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Insurances</h1>

<table>
  <thead>
    <tr>
      <th>Insurer</th>
      <th>Vehicule</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Insurance number</th>
      <th>Pre tax amount</th>
      <th>Vat rate</th>
      <th>Amount including tax</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurances.each do |insurance| %>
      <tr>
        <td><%= insurance.insurer %></td>
        <td><%= insurance.vehicule %></td>
        <td><%= insurance.start_date %></td>
        <td><%= insurance.end_date %></td>
        <td><%= insurance.insurance_number %></td>
        <td><%= insurance.pre_tax_amount %></td>
        <td><%= insurance.vat_rate %></td>
        <td><%= insurance.amount_including_tax %></td>
        <td><%= insurance.status %></td>
        <td><%= insurance.user %></td>
        <td><%= link_to 'Show', insurance %></td>
        <td><%= link_to 'Edit', edit_insurance_path(insurance) %></td>
        <td><%= link_to 'Destroy', insurance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insurance', new_insurance_path %>

app/views/insurances/new.html.erb
<h1>New Insurance</h1>

<%= render 'form', insurance: @insurance %>

<%= link_to 'Back', insurances_path %>

app/views/insurances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Insurer:</strong>
  <%= @insurance.insurer %>
</p>

<p>
  <strong>Vehicule:</strong>
  <%= @insurance.vehicule %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @insurance.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @insurance.end_date %>
</p>

<p>
  <strong>Insurance number:</strong>
  <%= @insurance.insurance_number %>
</p>

<p>
  <strong>Pre tax amount:</strong>
  <%= @insurance.pre_tax_amount %>
</p>

<p>
  <strong>Vat rate:</strong>
  <%= @insurance.vat_rate %>
</p>

<p>
  <strong>Amount including tax:</strong>
  <%= @insurance.amount_including_tax %>
</p>

<p>
  <strong>Status:</strong>
  <%= @insurance.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @insurance.user %>
</p>

<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>