config/routes.rb
Rails.application.routes.draw do
  resources :locations do   
    get "delete" 
  end

  resources :customers do   
    get "delete" 
  end

  resources :drivers do   
    get "delete" 
  end

  resources :expenses do   
    get "delete" 
  end
  resources :bookings do   
    get "delete" 
  end
  resources :rentals do   
    get "delete" 
  end
  resources :orders do   
    get "delete" 
  end
  resources :expense_types, path: "expense-types" do   
    get "delete" 
  end
  resources :maintenances do   
    get "delete" 
  end
  resources :consumptions do   
    get "delete" 
  end
  resources :intervention_types do   
    get "delete" 
  end
  resources :maintenance_types, path: "maintenance-types" do   
    get "delete" 
  end
  resources :vehicle_models do   
    get "delete" 
  end
  resources :odometers do   
    get "delete" 
  end
  
  resources :technical_visits do   
    get "delete" 
  end
  resources :insurances do   
    get "delete" 
  end
  resources :insurers do   
    get "delete" 
  end 
  resources :incidents do   
    get "delete" 
  end
  resources :parks do   
    get "delete" 
  end
  resources :gears do   
    get "delete" 
  end
  resources :gear_types, path: "gear-types" do   
    get "delete" 
  end
  resources :profiles do   
    get "delete" 
  end
  resources :permission_items do   
    get "delete" 
  end
  resources :permissions do   
    get "delete" 
  end
  resources :features do   
    get "delete" 
  end
  resources :roles do   
    get "delete" 
  end
  #root to: "front#home"

  get "/dashboard" => "dashboard#index", as: :dashboard
  resources :profiles do   
    get "delete" 
  end
  resources :permission_items do   
    get "delete" 
  end
  resources :permissions do   
    get "delete" 
  end
  resources :features do   
    get "delete" 
  end
  resources :roles do   
    get "delete" 
  end

  scope "account" do 
    resources :profiles 
    get "profile/:uid" => "profiles#edit", as: :edit_account
  end

  
  get "/users"     => "custom_users#index", as: :all_users 
  get "/users/unregistered"     => "custom_users#unregistered", as: :unregistered_commission_percentage 
  post "/users/new"     => "custom_users#create", as: :create_user
  get "/users/new"     => "custom_users#new", as: :new_user
  get "/user/edit/:id" => "custom_users#edit", as: :edit_user
  patch "/user/update/:id" => "custom_users#update", as: :update_user
  delete "/user/destroy/:id" => "custom_users#destroy", as: :destroy_user
  get "/user/delete/:id" => "custom_users#delete", as: :delete_user


  
  get "/user/enable/:id" => "custom_users#get_enable", as: :get_enable_user_account
  post "/user/enable/:id" => "custom_users#post_enable", as: :post_enable_user_account
  get "/user/disable/:id" => "custom_users#get_disable", as: :get_disable_user_account
  post "/user/disable/:id" => "custom_users#post_disable", as: :post_disable_user_account


  devise_for :users, path: '', controllers: { 
    registrations: "users/registrations",
    confirmations: 'users/confirmations',
    passwords: "users/passwords",
    sessions: "users/sessions"
        
    }, 
    path_names: {
        sign_in: 'login', 
        sign_out: 'logout', 
        password: 'secret', 
        confirmation: 'verification', 
        unlock: 'unblock', 
        registration: 'signup', 
        sign_up: '' 
    }
   
    devise_scope :user do
      root to: "users/sessions#new"
      authenticated :user do
        root 'dashboard#index', as: :authenticated_root
      end
  
      unauthenticated do
        root 'users/sessions#new', as: :unauthenticated_root
      end
    end


    # Dynamic error pages
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unacceptable"
    get "/500", to: "errors#internal_error"

    #mount Ckeditor::Engine => '/ckeditor'
  # For mobile API Endpoint
  #mount API::Base, at: "/"
end

app/models/permission_item.rb
# == Schema Information
#
# Table name: permission_items
#
#  id            :bigint           not null, primary key
#  uid           :string
#  permission_id :bigint
#  action_name   :string
#  status        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class PermissionItem < ApplicationRecord
    include SharedUtils::Generate
  
    
    before_save :generate_random_number_uid
    belongs_to :permission
   
    
    #validates :name, presence: true, uniqueness: true
  
   # Change default params ID to uid
	  def to_param
	    uid
	  end

  
  end
  

app/controllers/permission_items_controller.rb
class PermissionItemsController < ApplicationController
  before_action :set_permission_item, only: [:show, :edit, :update, :destroy]

  # GET /permission_items
  # GET /permission_items.json
  def index
    @permission_items = PermissionItem.all
  end

  # GET /permission_items/1
  # GET /permission_items/1.json
  def show
  end

  # GET /permission_items/new
  def new
    @permission_item = PermissionItem.new
  end

  # GET /permission_items/1/edit
  def edit
  end

  # POST /permission_items
  # POST /permission_items.json
  def create
    @permission_item = PermissionItem.new(permission_item_params)

    respond_to do |format|
      if @permission_item.save
        format.html { redirect_to @permission_item, notice: 'Permission item was successfully created.' }
        format.json { render :show, status: :created, location: @permission_item }
      else
        format.html { render :new }
        format.json { render json: @permission_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permission_items/1
  # PATCH/PUT /permission_items/1.json
  def update
    respond_to do |format|
      if @permission_item.update(permission_item_params)
        format.html { redirect_to @permission_item, notice: 'Permission item was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission_item }
      else
        format.html { render :edit }
        format.json { render json: @permission_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permission_items/1
  # DELETE /permission_items/1.json
  def destroy
    @permission_item.destroy
    respond_to do |format|
      format.html { redirect_to permission_items_url, notice: 'Permission item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission_item
      @permission_item = PermissionItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def permission_item_params
      params.require(:permission_item).permit(:uid, :permission_id, :action_name, :status)
    end
end

app/views/permission_items/_form.html.erb
<%= form_with(model: permission_item, local: true) do |form| %>
  <% if permission_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permission_item.errors.count, "error") %> prohibited this permission_item from being saved:</h2>

      <ul>
      <% permission_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uid %>
    <%= form.text_field :uid %>
  </div>

  <div class="field">
    <%= form.label :permission_id %>
    <%= form.text_field :permission_id %>
  </div>

  <div class="field">
    <%= form.label :action_name %>
    <%= form.text_field :action_name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/permission_items/edit.html.erb
<h1>Editing Permission Item</h1>

<%= render 'form', permission_item: @permission_item %>

<%= link_to 'Show', @permission_item %> |
<%= link_to 'Back', permission_items_path %>

app/views/permission_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permission Items</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Permission</th>
      <th>Action name</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permission_items.each do |permission_item| %>
      <tr>
        <td><%= permission_item.uid %></td>
        <td><%= permission_item.permission %></td>
        <td><%= permission_item.action_name %></td>
        <td><%= permission_item.status %></td>
        <td><%= link_to 'Show', permission_item %></td>
        <td><%= link_to 'Edit', edit_permission_item_path(permission_item) %></td>
        <td><%= link_to 'Destroy', permission_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permission Item', new_permission_item_path %>

app/views/permission_items/new.html.erb
<h1>New Permission Item</h1>

<%= render 'form', permission_item: @permission_item %>

<%= link_to 'Back', permission_items_path %>

app/views/permission_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @permission_item.uid %>
</p>

<p>
  <strong>Permission:</strong>
  <%= @permission_item.permission %>
</p>

<p>
  <strong>Action name:</strong>
  <%= @permission_item.action_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @permission_item.status %>
</p>

<%= link_to 'Edit', edit_permission_item_path(@permission_item) %> |
<%= link_to 'Back', permission_items_path %>